/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package trc.md.starter;

import com.mdaq.trc.marketdata.client.MarketDataSubscriber;
import com.mdaq.trc.marketdata.client.MarketDataSubscriberFactory;
import com.mdaq.trc.marketdata.client.model.SslConfig;

public class App {
    public static void main(String[] args) {
        ConnectionListener connectionListener = new ConnectionListener();
        MarketDataSubscriber subscriber = MarketDataSubscriberFactory.createSubscriber();
        SslConfig sslConfig = new SslConfig("test-ks-path", "test-ks-pw", "test-ts-path", "test-ts-pw");
        subscriber.connect("192.168.5.5", 23, "test-user", "test-pw", sslConfig, connectionListener);

        // Disconnect on application close
        // subscriber.disconnect();
    }
}
