/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package trc.md.starter;

import com.mdaq.trc.marketdata.client.MarketDataSubscriber;
import com.mdaq.trc.marketdata.client.MarketDataSubscriberFactory;
import com.mdaq.trc.marketdata.client.model.SslConfig;

public class App {
    public static void main(String[] args)  {
        ConnectionListener connectionListener = new ConnectionListener();
        MarketDataSubscriber subscriber = MarketDataSubscriberFactory.createSubscriber();

        String trustStorePath = "app/src/main/resources/client-uat.truststore";

//        SslConfig sslConfig = new SslConfig(null, null, trustStorePath, "gxw9dck*czu5XQW8azp");
        SslConfig sslConfig = new SslConfig(null, null, trustStorePath, "dslkkew77494*eee");
        subscriber.connect("13.250.15.157", 55100, "test-user", "test-pw", sslConfig, connectionListener);

        // Disconnect on application close
        // subscriber.disconnect();
    }
}
