/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package trc.md.starter;

import com.mdaq.trc.marketdata.client.MarketDataSubscriber;
import com.mdaq.trc.marketdata.client.MarketDataSubscriberFactory;
import com.mdaq.trc.marketdata.client.common.config.RetryConfig;
import com.mdaq.trc.marketdata.client.common.config.SslConfig;
import com.mdaq.trc.marketdata.client.common.config.SubscriberConfig;

public class App {
    public static void main(String[] args)  {
        ConnectionListener connectionListener = new ConnectionListener();
        MarketDataSubscriber subscriber = MarketDataSubscriberFactory.createSubscriber();

        String trustStorePath = "app/src/main/resources/client-uat.truststore";

        final var sslConfig = new SslConfig(null, null, trustStorePath, "dslkkew77494*eee");
        final var retryConfig = RetryConfig.builder().maxAttempts(-1).intervalMillis(5000).build() /* or RetryConfig.DISABLED to disable */;
        final var subscriberConfig = SubscriberConfig.builder().sslConfig(sslConfig).retryConfig(retryConfig).build();

        // Deprecated API
        // subscriber.connect("localhost", 55100, "test-user", "test-pw", sslConfig, connectionListener);

        subscriber.connect("localhost", 55100, "test-user", "test-pw", subscriberConfig, connectionListener);

        // Disconnect on application close
        // subscriber.disconnect();
    }
}
